version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_cuponera
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: cuponera
      MYSQL_USER: cuponera_user
      MYSQL_PASSWORD: cuponera123
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
